-- RepoScope admin monitoring support.
-- Applied to Supabase project boamqtcyvflgpewomfhj.
-- This is a versioned reference of the production SQL, not an executable migration file.

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  repository text,
  state text not null,
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  criteria_count integer check (criteria_count is null or criteria_count >= 0),
  created_at timestamptz not null default now()
);

create index if not exists usage_events_user_created_idx
  on public.usage_events (user_id, created_at desc);

create index if not exists usage_events_type_created_idx
  on public.usage_events (event_type, created_at desc);

alter table public.usage_events enable row level security;

-- No anon/authenticated policies by design: only server-side service_role telemetry.
revoke all on table public.usage_events from public, anon, authenticated;
grant select, insert, update, delete on table public.usage_events to service_role;
grant usage, select on sequence public.usage_events_id_seq to service_role;

create or replace function public.admin_session_snapshot()
returns table (
  session_id uuid,
  user_id uuid,
  email text,
  created_at timestamptz,
  updated_at timestamptz,
  refreshed_at timestamp,
  not_after timestamptz,
  user_agent text,
  ip text,
  active boolean
)
language sql
security definer
set search_path = pg_catalog, auth, public
as $$
  select
    s.id,
    s.user_id,
    u.email::text,
    s.created_at,
    s.updated_at,
    s.refreshed_at,
    s.not_after,
    s.user_agent,
    s.ip::text,
    (s.not_after is null or s.not_after > now()) as active
  from auth.sessions s
  join auth.users u on u.id = s.user_id
  where u.deleted_at is null
  order by coalesce(s.refreshed_at::timestamptz, s.updated_at, s.created_at) desc;
$$;

revoke all on function public.admin_session_snapshot() from public, anon, authenticated;
grant execute on function public.admin_session_snapshot() to service_role;
